# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxW3PCgFkQA2QDLplksq119d0AvpKw1i
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar los archivos CSV
ventas = pd.read_csv("ventas.csv", parse_dates=["fecha"])
productos = pd.read_csv("productos.csv")

# Unir ventas con productos para acceder a las categorías
ventas_prod = ventas.merge(productos, on="id_producto", how="left")

# Gráfico 1: Ventas por categoría de producto
plt.figure(figsize=(10, 6))
ventas_categoria = ventas_prod.groupby("categoria")["monto"].sum().sort_values(ascending=False)
sns.barplot(x=ventas_categoria.values, y=ventas_categoria.index)
plt.title("Ventas por categoría de producto")
plt.xlabel("Monto total vendido")
plt.ylabel("Categoría")
plt.tight_layout()
plt.savefig("ventas_por_categoria.png")  # Guardar gráfico
plt.show()

# Gráfico 3: Tendencia mensual de ventas
ventas_prod["mes"] = ventas_prod["fecha"].dt.to_period("M").astype(str)
ventas_mensual = ventas_prod.groupby("mes")["monto"].sum()

plt.figure(figsize=(10, 6))
ventas_mensual.plot(marker='o')
plt.title("Tendencia mensual de ventas")
plt.xlabel("Mes")
plt.ylabel("Monto total vendido")
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("tendencia_mensual_ventas.png")  # Guardar gráfico
plt.show()